using System.Collections.Generic;

namespace XingYeAPI.Other
{
    public static class List
    {
        // >===================== 假名相关 =====================< \\

        // 啊? 你在说什么? 你说这些列表和字典到底能干什么?
        // 拜托,这不就可以用来玩RP(角色扮演)了吗 :P

        /// <summary>
        /// 研究员的假名列表
        /// </summary>
        public static List<string> ResearcherPseudonyms = new List<string>
        {
            "Dr. Anomaly", "Dr. Aberration", "Dr. Quasar", "Dr. Paradox", "Dr. Nexus", "Dr. Obscura",
            "Dr. Parallax", "Dr. Vortex", "Dr. Specter", "Dr. Omega", "Dr. Enigma", "Dr. Obsidian",
            "Dr. Celestial", "Dr. Aether", "Dr. Cipher", "Dr. Mirage", "Dr. Illusion", "Dr. Abyss",
            "Dr. Horizon", "Dr. Zenith", "Dr. Aftermath", "Dr. Twilight", "Dr. Cataclysm", "Dr. Vertex",
            "Dr. Quantum", "Dr. Chimera", "Dr. Ethereal", "Dr. Nebula", "Dr. Lucid",
            "Dr. Rift", "Dr. Chronos", "Dr. Flux", "Dr. Cryptic", "Dr. Tempest", "Dr. Elysium",
            "Dr. Tesseract", "Dr. Folklore", "Dr. Infinity", "Dr. Elemental", "Dr. Hologram", "Dr. Spectral",
            "Dr. Eclipsed", "Dr. Alchemy", "Dr. Enclave", "Dr. Void", "Dr. Apex", "Dr. Arcane",
            "Dr. Prismatic", "Dr. Celestine", "Dr. Helix", "Dr. Ember", "Dr. Aetherial", "Dr. Fusion", "Dr. Lyric",
            "Dr. Nimbus", "Dr. Serendipity", "Dr. Catalyst", "Dr. Fathom", "Dr. Luminous", "Dr. Conundrum",
            "Dr. Ethos", "Dr. Parable", "Dr. Harbinger", "Dr. Echo", "Dr. Tranquil", "Dr. Solstice", "Dr. Spectrum",
            "Dr. Legacy", "Dr. Shimmer", "Dr. Wander", "Dr. Seraph", "Dr. Kaleidoscope", "Dr. Requiem", "Dr. Untamed",
            "Dr. Arcadia", "Dr. Chronicle", "Dr. Bizarre", "Dr. Frequency", "Dr. Luminary", "Dr. Myriad", "Dr. Aurora"
        };

        /// <summary>
        /// 研究员的全名字典
        /// </summary>
        public static Dictionary<string, string> ResearcherPseudonyms_FullNames = new Dictionary<string, string>
        {
            { "Dr. Anomaly", "Alice Anomaly" },
            { "Dr. Aberration", "Bobby Aberration" },
            { "Dr. Quasar", "Carl Quasar" },
            { "Dr. Paradox", "Diana Paradox" },
            { "Dr. Nexus", "Evelyn Nexus" },
            { "Dr. Obscura", "Felix Obscura" },
            { "Dr. Parallax", "George Parallax" },
            { "Dr. Vortex", "Hannah Vortex" },
            { "Dr. Specter", "Isaac Specter" },
            { "Dr. Omega", "Jasmine Omega" },
            { "Dr. Enigma", "Kyle Enigma" },
            { "Dr. Obsidian", "Lily Obsidian" },
            { "Dr. Celestial", "Mason Celestial" },
            { "Dr. Aether", "Nora Aether" },
            { "Dr. Cipher", "Oscar Cipher" },
            { "Dr. Mirage", "Paul Mirage" },
            { "Dr. Illusion", "Quinn Illusion" },
            { "Dr. Abyss", "Rachel Abyss" },
            { "Dr. Horizon", "Samuel Horizon" },
            { "Dr. Zenith", "Tina Zenith" },
            { "Dr. Aftermath", "Ulysses Aftermath" },
            { "Dr. Twilight", "Victor Twilight" },
            { "Dr. Cataclysm", "Wendy Cataclysm" },
            { "Dr. Vertex", "Xander Vertex" },
            { "Dr. Quantum", "Yara Quantum" },
            { "Dr. Chimera", "Zara Chimera" },
            { "Dr. Ethereal", "Aiden Ethereal" },
            { "Dr. Nebula", "Bella Nebula" },
            { "Dr. Lucid", "Cameron Lucid" },
            { "Dr. Rift", "Dominic Rift" },
            { "Dr. Chronos", "Emilia Chronos" },
            { "Dr. Flux", "Fiona Flux" },
            { "Dr. Cryptic", "Gina Cryptic" },
            { "Dr. Tempest", "Henry Tempest" },
            { "Dr. Elysium", "Isla Elysium" },
            { "Dr. Tesseract", "Jack Tesseract" },
            { "Dr. Folklore", "Kira Folklore" },
            { "Dr. Infinity", "Leo Infinity" },
            { "Dr. Elemental", "Mila Elemental" },
            { "Dr. Hologram", "Noah Hologram" },
            { "Dr. Spectral", "Olivia Spectral" },
            { "Dr. Eclipsed", "Piper Eclipsed" },
            { "Dr. Alchemy", "Quincy Alchemy" },
            { "Dr. Enclave", "Riley Enclave" },
            { "Dr. Void", "Sophie Void" },
            { "Dr. Apex", "Theo Apex" },
            { "Dr. Arcane", "Uma Arcane" },
            { "Dr. Prismatic", "Vera Prismatic" },
            { "Dr. Celestine", "William Celestine" },
            { "Dr. Helix", "Xena Helix" },
            { "Dr. Ember", "Yusuf Ember" },
            { "Dr. Aetherial", "Zara Aetherial" },
            { "Dr. Fusion", "Adrian Fusion" },
            { "Dr. Lyric", "Brianna Lyric" },
            { "Dr. Nimbus", "Caleb Nimbus" },
            { "Dr. Serendipity", "Dahlia Serendipity" },
            { "Dr. Catalyst", "Evan Catalyst" },
            { "Dr. Fathom", "Freya Fathom" },
            { "Dr. Luminous", "Gabe Luminous" },
            { "Dr. Conundrum", "Holly Conundrum" },
            { "Dr. Ethos", "Ivy Ethos" },
            { "Dr. Parable", "Jace Parable" },
            { "Dr. Harbinger", "Kendall Harbinger" },
            { "Dr. Echo", "Layla Echo" },
            { "Dr. Tranquil", "Miles Tranquil" },
            { "Dr. Solstice", "Nina Solstice" },
            { "Dr. Spectrum", "Owen Spectrum" },
            { "Dr. Legacy", "Paige Legacy" },
            { "Dr. Shimmer", "Quinn Shimmer" },
            { "Dr. Wander", "Ryder Wander" },
            { "Dr. Seraph", "Siena Seraph" },
            { "Dr. Kaleidoscope", "Tobias Kaleidoscope" },
            { "Dr. Requiem", "Violet Requiem" },
            { "Dr. Untamed", "Wyatt Untamed" },
            { "Dr. Arcadia", "Zoe Arcadia" },
            { "Dr. Chronicle", "Aaron Chronicle" },
            { "Dr. Bizarre", "Brenda Bizarre" },
            { "Dr. Frequency", "Charlie Frequency" },
            { "Dr. Luminary", "Freddie Luminary" },
            { "Dr. Myriad", "Greta Myriad" },
            { "Dr. Aurora", "Henry Aurora" }
        };

        /// <summary>
        /// 特工的假名列表
        /// </summary>
        public static List<string> AgentPseudonyms = new List<string>
        {
            "Agent Raptor", "Agent Shadow", "Agent Viper", "Agent Ghost",
            "Agent Phantom", "Agent Wraith", "Agent Specter", "Agent Raven",
            "Agent Obsidian", "Agent Cyclone", "Agent Tempest", "Agent Frost",
            "Agent Blaze", "Agent Cinder", "Agent Quake", "Agent Pulse",
            "Agent Echo", "Agent Striker", "Agent Scorpion", "Agent Inferno",
            "Agent Venom", "Agent Steel", "Agent Alpha", "Agent Omega",
            "Agent Sentinel", "Agent Oracle", "Agent Rift", "Agent Spectra",
            "Agent Quantum", "Agent Cipher", "Agent Jester", "Agent Nova",
            "Agent Chameleon", "Agent Mirage", "Agent Dusk", "Agent Zenith",
            "Agent Vortex", "Agent Nebula", "Agent Comet", "Agent Polaris",
            "Agent Ember", "Agent Serpent", "Agent Catalyst", "Agent Reaper",
            "Agent Vigilante", "Agent Paradox", "Agent Seraph", "Agent Nomad",
            "Agent Dynamo", "Agent Keystone", "Agent Sterling",
            "Agent Talisman", "Agent Sable", "Agent Reckoning", "Agent Warden",
            "Agent Fracture", "Agent Apex", "Agent Horizon", "Agent Solstice",
            "Agent Phoenix", "Agent Arcane", "Agent Vengeance", "Agent Titan",
            "Agent Fallout", "Agent Stratus", "Agent Haze", "Agent Fable",
            "Agent Reactor", "Agent Nightshade", "Agent Golem", "Agent Valor",
            "Agent Luminary", "Agent Strider", "Agent Abyss", "Agent Ashes",
            "Agent Atlas", "Agent Legacy", "Agent Ward", "Agent Cryptic",
            "Agent Fission", "Agent Elysium", "Agent Drift", "Agent Dolce",
            "Agent Vanguard", "Agent Surge", "Agent Code", "Agent Thorne",
            "Agent Nighthawk", "Agent Haven", "Agent Locus", "Agent Feral",
            "Agent Equinox", "Agent Havoc", "Agent Resistance", "Agent Mistral",
            "Agent Gloom", "Agent Plague", "Agent Radiant", "Agent Stalker",
            "Agent Kismet", "Agent Volt"
        };

        /// <summary>
        /// 特工的全名字典
        /// </summary>
        public static Dictionary<string, string> AgentPseudonyms_FullNames = new Dictionary<string, string>
        {
            { "Agent Raptor", "Ryan Raptor" },
            { "Agent Shadow", "Samantha Shadow" },
            { "Agent Viper", "Victor Viper" },
            { "Agent Ghost", "Grace Ghost" },
            { "Agent Phantom", "Philip Phantom" },
            { "Agent Wraith", "Wanda Wraith" },
            { "Agent Specter", "Simon Specter" },
            { "Agent Raven", "Rebecca Raven" },
            { "Agent Obsidian", "Oliver Obsidian" },
            { "Agent Cyclone", "Cathy Cyclone" },
            { "Agent Tempest", "Thomas Tempest" },
            { "Agent Frost", "Fiona Frost" },
            { "Agent Blaze", "Brandon Blaze" },
            { "Agent Cinder", "Celeste Cinder" },
            { "Agent Quake", "Quincy Quake" },
            { "Agent Pulse", "Paige Pulse" },
            { "Agent Echo", "Ethan Echo" },
            { "Agent Striker", "Sophie Striker" },
            { "Agent Scorpion", "Sean Scorpion" },
            { "Agent Inferno", "Ivy Inferno" },
            { "Agent Venom", "Victor Venom" },
            { "Agent Steel", "Savannah Steel" },
            { "Agent Alpha", "Angela Alpha" },
            { "Agent Omega", "Owen Omega" },
            { "Agent Sentinel", "Sandra Sentinel" },
            { "Agent Oracle", "Oliver Oracle" },
            { "Agent Rift", "Rachel Rift" },
            { "Agent Spectra", "Sebastian Spectra" },
            { "Agent Quantum", "Quinn Quantum" },
            { "Agent Cipher", "Clara Cipher" },
            { "Agent Jester", "James Jester" },
            { "Agent Nova", "Nina Nova" },
            { "Agent Chameleon", "Chris Chameleon" },
            { "Agent Mirage", "Molly Mirage" },
            { "Agent Dusk", "Derek Dusk" },
            { "Agent Zenith", "Zara Zenith" },
            { "Agent Vortex", "Victor Vortex" },
            { "Agent Nebula", "Nate Nebula" },
            { "Agent Comet", "Cindy Comet" },
            { "Agent Polaris", "Peter Polaris" },
            { "Agent Ember", "Emma Ember" },
            { "Agent Serpent", "Simon Serpent" },
            { "Agent Catalyst", "Cathy Catalyst" },
            { "Agent Reaper", "Rachel Reaper" },
            { "Agent Vigilante", "Victor Vigilante" },
            { "Agent Paradox", "Perry Paradox" },
            { "Agent Seraph", "Sophie Seraph" },
            { "Agent Nomad", "Nina Nomad" },
            { "Agent Dynamo", "Daniel Dynamo" },
            { "Agent Keystone", "Kathy Keystone" },
            { "Agent Sterling", "Alex Sterling" },
            { "Agent Talisman", "Tina Talisman" },
            { "Agent Sable", "Sofia Sable" },
            { "Agent Reckoning", "Rob Reckoning" },
            { "Agent Warden", "Will Warden" },
            { "Agent Fracture", "Felicity Fracture" },
            { "Agent Apex", "Aiden Apex" },
            { "Agent Horizon", "Hannah Horizon" },
            { "Agent Solstice", "Samuel Solstice" },
            { "Agent Phoenix", "Paula Phoenix" },
            { "Agent Arcane", "Amelia Arcane" },
            { "Agent Vengeance", "Vincent Vengeance" },
            { "Agent Titan", "Tessa Titan" },
            { "Agent Fallout", "Frank Fallout" },
            { "Agent Stratus", "Stella Stratus" },
            { "Agent Haze", "Harper Haze" },
            { "Agent Fable", "Finn Fable" },
            { "Agent Reactor", "Rita Reactor" },
            { "Agent Nightshade", "Ethan Nightshade" },
            { "Agent Golem", "Graham Golem" },
            { "Agent Valor", "Victoria Valor" },
            { "Agent Luminary", "Lucy Luminary" },
            { "Agent Strider", "Simon Strider" },
            { "Agent Abyss", "Abigail Abyss" },
            { "Agent Ashes", "Aaron Ashes" },
            { "Agent Atlas", "Nathanael Atlas" },
            { "Agent Legacy", "Liam Legacy" },
            { "Agent Ward", "Caleb Ward" },
            { "Agent Cryptic", "Cameron Cryptic" },
            { "Agent Fission", "Felicia Fission" },
            { "Agent Elysium", "Elena Elysium" },
            { "Agent Drift", "Dylan Drift" },
            { "Agent Dolce", "Dawn Dolce" },
            { "Agent Vanguard", "Victor Vanguard" },
            { "Agent Surge", "Selena Surge" },
            { "Agent Code", "Derek Code" },
            { "Agent Thorne", "Tori Thorne" },
            { "Agent Nighthawk", "Nina Nighthawk" },
            { "Agent Haven", "Henry Haven" },
            { "Agent Locus", "Leah Locus" },
            { "Agent Feral", "Frank Feral" },
            { "Agent Equinox", "Eli Equinox" },
            { "Agent Havoc", "Holly Havoc" },
            { "Agent Resistance", "Ron Resistance" },
            { "Agent Mistral", "Mia Mistral" },
            { "Agent Gloom", "Gina Gloom" },
            { "Agent Plague", "Perry Plague" },
            { "Agent Radiant", "Rachel Radiant" },
            { "Agent Stalker", "Simon Stalker" },
            { "Agent Kismet", "Kyla Kismet" },
            { "Agent Volt", "Liam Volt" }
        };

        /// <summary>
        /// 通用全名列表
        /// </summary>
        public static List<string> Common_FullNames = new List<string>
        {
            "Liam Johnson", "Emma Smith", "Olivia Williams", "Noah Brown",
            "Ava Jones", "Oliver Garcia", "Isabella Miller", "Elijah Davis",
            "Sophia Rodriguez", "James Martinez", "Mia Hernandez", "Lucas Thompson",
            "Amelia Anderson", "Mason Taylor", "Harper Wilson", "Ethan Moore",
            "Evelyn Jackson", "Logan White", "Abigail Harris", "Jackson Martin",
            "Ella Thompson", "Aiden Lee", "Scarlett Hall", "Alexander Young",
            "Sofia Allen", "Benjamin King", "Avery Wright", "Carter Scott",
            "Kamryn Turner", "Matthew Adams", "Chloe Perez", "Michael Nelson",
            "Grace Carter", "Henry Mitchell", "Natalie Roberts", "Jackson Smith",
            "Victoria Gomez", "Samuel Cooper", "Hannah Phillips", "Andrew Reed",
            "Aria Evans", "Jacob Rivera", "Zoe Campbell", "William Campbell",
            "Ella Parker", "Isaiah Edwards", "Riley Edwards", "Nathan Jenkins",
            "Layla Collins", "Lucas Ward", "Maddox Flores", "Peyton Wood",
            "Adam Ramirez", "Anna Brooks", "Aaron Bennett", "Victoria Hughes",
            "Nicholas Sanders", "Juliana Price", "Daniel Russell", "Madison Hill",
            "Levi Hughes", "Chloe Ward", "Milo Peterson", "Aaliyah Murphy",
            "Ian Stewart", "Savannah Ramirez", "Gavin Torres", "Maya Hill",
            "Jaxon Rivera", "Bella Bennett", "Robert Ross", "Jasmine Flores",
            "Nolan Murphy", "Lucy Rogers", "Miguel Rivera", "Abigail Cooper",
            "Jace Lee", "Isabelle Peterson", "Aidan Fisher", "Nylah Edwards",
            "Jesse Johnson", "Gianna Adams", "Ryder Stewart", "Jessica Flores",
            "Alan Edwards", "Mira Reed", "Paul Ramirez", "Sylvia Bailey",
            "Kyle Cox", "Hazel Kelly", "Eli Foster", "Eva Sanders",
            "Tyler Reed", "Jada Bell", "Carlos Price", "Ella Hall",
            "Marcus Price", "Megan Murphy", "Isaiah Gordon", "Scarlett Marshall",
            "Caleb Young", "Lydia Parker", "Dylan Sims", "Jordan Murray",
            "Diego Schmidt", "Kaylee Bennett", "Timothy Kelly", "Emma Perkins",
            "Cameron Hughes", "Summer Grant", "Beckett Mason", "Megan Baker",
            "Zachary Reed", "Lydia Bailey", "Victor Martinez", "Aaron Cruz",
            "Sawyer Wright", "London Daniels", "Finn Parker", "Eleanor Cooper",
            "Santiago Morgan", "Jocelyn Rivera", "Cody Hart", "Elena Mills",
            "Eric James", "Keira Reed", "Grant Harrison", "Amy Patterson",
            "Trevor Price", "Maria Garcia", "Colton Lee", "Alivia Campbell",
            "Kaden Nelson", "Harlow Bennett", "Ronin Reyes", "Amy Martinez",
            "Kai Johnson", "Maya Brooks", "Riley Diaz", "Samantha Myers",
            "Bryce Ray", "Olivia Young", "Arthur Butler", "Megan Lopez",
            "Gage Robbins", "Josie Ramirez", "Harrison Torres", "Hannah Sanchez",
            "Brynn Jimenez", "Liam Wolf", "Aaliyah Soto", "Ruben Parker",
            "Maya Sanchez", "Aurora Brooks", "Maverick Gonzalez", "Nina Bennett",
            "Bradley Martinez", "Leslie Reed", "Victor Hall", "Genesis Torres",
            "Carmen Ruiz", "Sofia Murphy", "Landon Murray", "Adeline Jones",
            "Adrian Bell", "Piper Williams", "Cecilia Martinez", "Annie Sullivan",
            "Kylie Rivers", "Logan Murphy", "Faith Evans", "Bianca White",
            "Jayden Collins", "Danielle Lee", "Makayla Green", "Brody Walker",
            "Clara Harris", "Peter Parker", "Fiona Adkins", "Matthew Wright",
            "Rudy Moore", "Sienna Harris", "Harrison Thompson", "Mabel Cooper",
            "Graham White", "Chase Phillips", "Brooklyn Reed", "Ricardo Davis",
            "Kendall Bennett", "Kara Morris", "Bradley Diaz", "Lola Lopez",
            "Blake Turner", "Joanna Ramirez", "Sawyer Gonzalez", "Ivy Martin",
            "Iris Rivera", "Maxwell Martinez", "Rowan Davis", "Jennifer Green"
        };

        // >===================== 假名相关 =====================< \\
    }
}